# Generated by Django 4.1.5 on 2023-02-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_alter_message_receiver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chats',
        ),
    ]
