# Generated by Django 4.1.5 on 2023-02-07 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_remove_room_target_roomusers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user_id',
            new_name='user',
        ),
    ]
