# Generated by Django 4.1.5 on 2023-02-07 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_rename_user_id_room_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='user',
            new_name='username',
        ),
    ]
